# Generated by Django 2.1.7 on 2019-02-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Назвние вакансии')),
                ('short_description', models.TextField(verbose_name='Краткое описание вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='з/п от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='з/п до')),
                ('currency', models.CharField(blank=True, max_length=4, null=True, verbose_name='Валюта з/п')),
                ('link', models.URLField(max_length=60, verbose_name='Ссылка на вакансию')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'Vacancy',
            },
        ),
    ]
